---
# Original role: Nagios NRPE Server role by Mooash
- name: NRPE | Include OS-Specific variables
  tags:
    - nrpe
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ansible_distribution}}_{{ansible_distribution_major_version}}_{{ansible_distribution_minor_version}}.yml"
    - "{{ansible_distribution}}_{{ansible_distribution_major_version}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}_{{ansible_distribution_major_version}}_{{ansible_distribution_minor_version}}.yml"
    - "{{ansible_os_family}}_{{ansible_distribution_major_version}}.yml"
    - "{{ansible_os_family}}.yml"
    - default.yml

- name: NRPE | Assert that OS is supported
  tags:
    - nrpe
  assert:
    that: nrpe_os_supported == True

- name: nrpe | Set facts for nrpe_manage_service and nrpe_allow_restart
  tags:
    - nrpe
  set_fact:
    nrpe_manage_service: "{{ false if ansible_virtualization_type == 'docker' else true }}"
    nrpe_allow_restart: "{{ false if ansible_virtualization_type == 'docker' else true }}"

- name: NRPE | Install Nagios NRPE Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ nrpe_packages }}"

- name: Create nrpe.cfg from template
  template:
    src: "nrpe.cfg.j2"
    dest: "{{ nrpe_dir }}/nrpe.cfg"
    owner: root
    group: root
    mode: "0644"
  notify: Restart NRPE

- name: Create nrpe_ansible.cfg from template
  template:
    src: "nrpe_d.cfg.j2"
    dest: "{{ nagios_nrpe_server_dir }}/nrpe_ansible.cfg"
    owner: root
    group: root
    mode: "0644"
  notify: Restart NRPE

- name: Install global plugins
  copy:
    src: "{{ item }}"
    dest: "{{ nagios_nrpe_server_plugins_dir }}/"
    owner: root
    group: root
    mode: "0755"
  with_fileglob:
    - {{ datadir }}/plugins/global/*

- name: Install per-server plugins
  copy:
    src: "{{ item }}"
    dest: "{{ nagios_nrpe_server_plugins_dir }}/"
    owner: root
    group: root
    mode: "0755"
  with_fileglob:
    - "{{ datadir }}/plugins/{{ ansible_fqdn }}/*"

- name: Ensure NRPE server is running
  service:
    name: "{{ nagios_nrpe_server_service }}"
    state: started
    enabled: yes
