---
#*
#* ## Handlers
#*
#* ### Restart NRPE
#*
#* Restarts the Nagios NRPE Service
#*
#* Since RedHat based OS's and Debian based ones call the service
#* different names, we use a variable set in vars/{{ ansible\_os\_family }}.yml
#*

- name: Restart NRPE
  service:
    name: "{{ nrpe_service }}"
    state: restarted
  when: nrpe_allow_restart
